apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: focalboard-ingress
  namespace: default
spec:
  rules:
    - host:
      http:
        paths:
          - path: /focus
            pathType: Prefix
            backend:
              service:
                name:  my-focalboard
                port:
                  number: 8000