apiVersion: v1
data:
  config.json: |
    {
      "serverRoot": "http://localhost:8000",
      "port": 8000,
      "dbtype": "sqlite3",
      "dbconfig": "/data/focalboard.db",
      "postgres_dbconfig": "dbname=focalboard sslmode=disable",
      "useSSL": false,
      "webpath": "./pack",
      "filespath": "/data/files",
      "telemetry": true,
      "session_expire_time": 2592000,
      "session_refresh_time": 18000,
      "localOnly": false,
      "enableLocalMode": true,
      "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: focalboard
    meta.helm.sh/release-namespace: documentation
  creationTimestamp: "2024-11-04T01:50:54Z"
  labels:
    app.kubernetes.io/instance: focalboard
    app.kubernetes.io/name: focalboard
  name: focalboard-config
  namespace: documentation
