apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- podinfo-release.yaml
- podinfo-repo.yaml
- podinfo-chart.yaml
- podinfo-ingress.yaml
- podinfo-lb.yaml
