apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://metallb.github.io/metallb
  ref:
    tag: 0.14.8