apiVersion: v1
kind: Service
metadata:
  name: podinfo-load
  namespace: default
spec:
  selector:
    app: podinfo
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9898
      targetPort: 9898