apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chartRef:
    kind: GitRepository
    name: traefik
    namespace: flux-system
  interval: 10m
  values:
    replicaCount: 2