apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  chartRef:
    kind: HelmChart
    name: monitoring
    namespace: monitoring
  interval: 10m
  values:
    replicaCount: 1
