apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  chartRef:
    kind: HelmChart
    name: metallb
    namespace: metallb
  interval: 10m
  values:
    replicaCount: 2